### ISSUE TITLE
you need to change the command path

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [SL-RU/mmt#2]
`Command("/home/lyra/slf/mmt/target/debug/mmt"):cwd("/"):stdin(Command.INHERIT):stdout(Command.PIPED):stderr(
`

not everyone has the same username, and it should probably look for mmt in $PATH instead

**Comment by SL-RU** [comment]
Hi, sorry, I've forgot to push commit. Can you check again https://github.com/SL-RU/mount.yazi and take attention to readme

**Comment by 4rtemis-4rrow** [comment]
that does work, but I still think you should just use $PATH

meaning, just run `mmt`

better UX

**Comment by SL-RU** [comment]
Okay, then the binary from PATH will be a default option, but if arg will be passed then it'll override default

**Comment by 4rtemis-4rrow** [comment]
ok I see, yeah that's a great idea

**Comment by SL-RU** [comment]
Done, now if argument is not set then mmt will be got from PATH:  https://github.com/SL-RU/mount.yazi
